Redundant pcc unseal text
riscv/riscv-cheri pull request #124
Opened 2024-02-21 12:51 UTC by tariqkurd-repo

remove redundant exception check for the PCC being sealed

2024-02-21 13:02 UTC, francislaus requested changes
This does not match the result of the discussion in #112 if I understand your PR correctly.

2024-02-22 15:58 UTC, tariqkurd-repo commented
@francislaus this PR is saying that there can't be an exception caused by the PCC being sealed, so I've removed that from the exception table

2024-02-23 12:00 UTC, andresag01 approved these changes

2024-02-23 17:17 UTC, arichardson commented on src/riscv-integration.adoc
> +^1^ this check is architecturally required, but is not required in an implementation
```suggestion
^1^ This check is architecturally required, but is impossible to encounter so may not required in an implementation.
```

Maybe like this?

2024-02-23 17:17 UTC, arichardson approved these changes
LGTM with the footnote changes to a full sentence.

2024-02-23 21:56 UTC, merged