Merge Zcheri_mode and Zcheri_legacy
riscv/riscv-cheri pull request #161
Opened 2024-04-01 23:39 UTC by arichardson

The main reason for a separate Zcheri_mode extensions is that it freed
up a bit from the 32-bit capability format. With a new 32-bit
permissions encoding (https://github.com/riscv/riscv-cheri/pull/155), we
need less than a full bit for the mode since it is only required for
executable capabilities rather than fully orthogonal. Removing the
separate Zcheri_mode extension simplifies the architecture and will
allow for further simplification of the CME architectural state.

2024-04-02 00:20 UTC, arichardson commented
CC: @sorear

2024-04-02 16:23 UTC, arichardson commented on src/riscv-mode-integration.adoc
> -{cheri_mode_ext_name} adds a new CHERI execution mode bit (M) to capabilities.
We can probably fold this file into riscv-legacy-integration.adoc, but I wanted to keep the changes smaller initially.

2024-04-03 12:55 UTC, tariqkurd-repo commented on src/riscv-legacy-integration.adoc
> +NOTE: <<JALR_MODE>> can be used to change the current CHERI execution mode.
not any more - and I merged the jalr.mode PR so I'm not sure why this section is still here

2024-04-04 09:05 UTC, andresag01 requested changes
Thanks for the changes. It looks good, just a few minor comments. It would be good to rebase this on top of the latest main which has the CME bits removal.

2024-04-04 13:25 UTC, andresag01 commented
@tariqkurd-repo @arichardson : I cherry picked the commit removing the CRE bit and re-arranged the Zcheri_legacy chapter a little. Here are my changes in case they are helpful: https://github.com/andresag01/riscv-cheri/commits/users/arichardson/spr/merge-zcheri_mode-and-zcheri_legacy/

2024-04-04 14:14 UTC, arichardson commented on src/riscv-legacy-integration.adoc
>  [#section_legacy_ext_instructions]
Thanks for your changes, this should be resolved now.

2024-04-04 14:27 UTC, andresag01 approved these changes

2024-04-04 16:09 UTC, merged