Remove the CHERI mode enable CSR bits
riscv/riscv-cheri pull request #162
Opened 2024-04-02 00:19 UTC by arichardson

With the mode bit of PCC always present when legacy mode is available,
we no longer need a separate out-of-band state bit to indicate the
current mode. The CHERI register enable (CRE) bit remains present to
prevent access to CHERI instruction and mseccfg.CME was changed to
behave as a register enable bit for M-mode.

Having the mode bit always present ensures that we can set the execution
mode for trap handlers without affecting the mode of other code.

2024-04-02 00:21 UTC, arichardson commented
CC: @sorear

This relates to https://github.com/riscv/riscv-cheri/pull/130, moving all CHERI mode state to PCC and out of xenvcfg.

2024-04-03 12:33 UTC, tariqkurd-repo commented on src/img/menvcfgmodereg.edn
> +(draw-box (text "WPRI" {:font-weight "bold"}) {:span 9})
This isn't rendering correctly

<img width="569" alt="image" src="https://github.com/riscv/riscv-cheri/assets/59061376/eeee8cab-18a4-4f14-829e-af32d8aea6d4">

and it's only 1 bit in the text, not 2

2024-04-03 12:38 UTC, tariqkurd-repo requested changes
two minor fixes required as listed, otherwise LGTM

2024-04-03 12:38 UTC, tariqkurd-repo commented on src/img/senvcfgreg.edn
> +(draw-box (text "WPRI" {:font-weight "bold" :font-size 20}) {:span 6})
This has the same problem as menvcfg

<img width="582" alt="image" src="https://github.com/riscv/riscv-cheri/assets/59061376/8a2c99fd-deb2-4f4d-a494-f98fb14640ab">

2024-04-03 13:55 UTC, andresag01 commented
@tariqkurd-repo : Could you review again? I fixed the bit indexes in xenvcfg diagrams

2024-04-03 14:36 UTC, merged

2024-04-03 14:48 UTC, andresag01 commented
@tariqkurd-repo @arichardson : This was merged onto an alternate branch instead of main. We need to merge it into main if we are happy with the changes

2024-04-03 15:35 UTC, arichardson commented
> @tariqkurd-repo @arichardson : This was merged onto an alternate branch instead of main. We need to merge it into main if we are happy with the changes

I think the easiest way will be to recreate this PR and merge it. Will do so shortly.

2024-04-04 17:59 UTC, sorear commented
I will most likely not be able to look at any CHERI-related issues until two weeks from now.