Remove support for downloading CSVs from Google Docs
riscv/riscv-cheri pull request #497
Opened 2024-12-20 10:45 UTC by Timmmm

The Google version hasn't been kept up to date with the version in the repo, and it's a bit weird to still have this anyway.

Fixes #496

2024-12-20 15:04 UTC, tariqkurd-repo commented
There is one bug fix in the google sheet which hasn't made it to an MR yet - @francislaus are you planning to do that?
I'm not planning to remove the google sheet as maintaining the CSV without it will be a real pain, we'll need a flow for doing that (possibly to/fromyaml) first.

2024-12-20 15:05 UTC, tariqkurd-repo requested changes
Not until a replacement flow is in place to allow easy maintainance.

2024-12-20 16:43 UTC, Timmmm commented
You can edit the CSV directly using a CSV editor no? I don't see any features except for colours that are used in the Google Doc that aren't preserved in the CSV.

Here's [one I like in VSCode](https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv):

![image](https://github.com/user-attachments/assets/0f01a3d5-f060-4081-9feb-e7dd89abaff6)

It's write format doesn't *quite* match what Google Docs outputs (Google outputs `,"",` for empty fields), but they seem to be on their own there. LibreOffice and Gnumeric and that extension just do `,,` so I'd suggest just switching to that.

2024-12-30 17:58 UTC, arichardson commented
I also think it's time to change the source of truth to be the repository. I can also edit the CSV as a table in Intellij:

![image](https://github.com/user-attachments/assets/bdc30c7a-1a49-41d8-b04a-3c0b72974169)

We could convert it to YAML to make it easier to edit, but I'm not sure that's really necessary?

2025-01-02 10:14 UTC, tariqkurd-repo commented
> We could convert it to YAML to make it easier to edit, but I'm not sure that's really necessary?

the point of yaml is to make the differences easier to spot, but as the spreadsheet is fairly small it's probably not so important

also the spreadsheet as a lot of repeated entries, which are lost when converting to CSV, so it's possible that text will diverge (e.g. a lot of CSRs have the same `Update the CSR using <<SCADDR>>.` text

Additionally. which is also important, a huge advantage of the spreadsheet is filtering and sorting columns which I can't obviously see how to do in EditCSV. The information is quite stable so maybe it's not so important not but these spreadsheet features have made a lot of difference when developing the spec.

2025-01-02 10:15 UTC, tariqkurd-repo approved these changes

2025-01-02 10:15 UTC, merged